apiVersion: batch/v1
kind: Job
metadata:
  name: keycloak-config-cli
  namespace: keycloak
  labels:
    app: keycloak-config-cli
spec:
  backoffLimit: 3
  template:
    spec:
      initContainers:
        - name: wait-for-keycloak
          image: bitnamilegacy/keycloak:26.3.1-debian-12-r1
          command:
            - sh
            - -c
            - |
              echo "Esperando a que Keycloak este listo..."
              until curl -sf http://keycloak.keycloak.svc.cluster.local/realms/master; do
                echo "Reintentando en 10s..."
                sleep 10
              done
              echo "Keycloak listo."
      containers:
        - name: keycloak-config-cli
          image: quay.io/adorsys/keycloak-config-cli:v6.1.4-26.0.5
          env:
            - name: KEYCLOAK_URL
              value: "http://keycloak.keycloak.svc.cluster.local"
            - name: KEYCLOAK_USER
              value: "admin"
            - name: KEYCLOAK_PASSWORD
              value: "admin1234"
            - name: IMPORT_FILES_LOCATIONS
              value: "/config/*"
            - name: LOGGING_LEVEL_ROOT
              value: "INFO"
          volumeMounts:
            - name: realm-config
              mountPath: /config
              readOnly: true
      volumes:
        - name: realm-config
          configMap:
            name: keycloak-realm-config
      restartPolicy: Never
